#!/bin/sh

if [ -z "$1" ]
then
	input=.
else
	input=$1
fi

if [ -z "$2" ]
then
	if [ $input = "." ]
	then
		output=$(basename $PWD).uzbl
	else
		output=$(basename $input).uzbl
	fi
else
	output=$2
fi

[ -f "$input/version" ] && uzbl-core -V > "$input/version"

#for f in $(ls "$input/scripts")
#do
#	sed -e "s|\$XDG_DATA_HOME/uzbl/scripts|$EXTENSION_DIRECTORY/$NAME/scripts|g" -f $f
#done

#tar cf $output $input
( cd $input && tar cfz ../$output . )
